# fly.toml app configuration file generated for client-still-glade-2773 on 2024-08-03T05:39:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'client-still-glade-2773'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
